import { Template } from '../types';

export const TEMPLATES: Template[] = [
  {
    id: 'solid-dark',
    name: 'Midnight',
    type: 'solid',
    background: '#18181b',
    defaultPadding: 40,
    defaultTextColor: '#ffffff',
  },
  {
    id: 'solid-light',
    name: 'Paper',
    type: 'solid',
    background: '#f4f4f5',
    defaultPadding: 40,
    defaultTextColor: '#18181b',
  },
  {
    id: 'solid-brand',
    name: 'Brand',
    type: 'solid',
    background: '#2563eb',
    defaultPadding: 40,
    defaultTextColor: '#ffffff',
  },
  {
    id: 'solid-rose',
    name: 'Rose',
    type: 'solid',
    background: '#ffe4e6',
    defaultPadding: 40,
    defaultTextColor: '#881337',
  },
  {
    id: 'grad-sunset',
    name: 'Sunset',
    type: 'gradient',
    background: 'linear-gradient(to bottom right, #f97316, #eab308)',
    defaultPadding: 40,
    defaultTextColor: '#ffffff',
  },
  {
    id: 'grad-ocean',
    name: 'Ocean',
    type: 'gradient',
    background: 'linear-gradient(to bottom right, #0ea5e9, #3b82f6)',
    defaultPadding: 40,
    defaultTextColor: '#ffffff',
  },
  {
    id: 'grad-aurora',
    name: 'Aurora',
    type: 'gradient',
    background: 'linear-gradient(to bottom right, #10b981, #3b82f6)',
    defaultPadding: 40,
    defaultTextColor: '#ffffff',
  },
  {
    id: 'grad-twilight',
    name: 'Twilight',
    type: 'gradient',
    background: 'linear-gradient(to bottom right, #8b5cf6, #ec4899)',
    defaultPadding: 40,
    defaultTextColor: '#ffffff',
  },
  {
    id: 'pattern-dots',
    name: 'Dots',
    type: 'pattern',
    background: 'radial-gradient(#cbd5e1 2px, transparent 2px)',
    defaultPadding: 40,
    defaultTextColor: '#1e293b',
  },
  {
    id: 'pattern-grid',
    name: 'Grid',
    type: 'pattern',
    background: 'linear-gradient(#e2e8f0 1px, transparent 1px), linear-gradient(90deg, #e2e8f0 1px, transparent 1px)',
    defaultPadding: 40,
    defaultTextColor: '#0f172a',
  },
  {
    id: 'photo-nature',
    name: 'Nature',
    type: 'photo',
    background: 'https://images.unsplash.com/photo-1472214103451-9374bd1c798e?auto=format&fit=crop&w=1080&q=80',
    defaultPadding: 40,
    defaultTextColor: '#ffffff',
  },
  {
    id: 'photo-custom',
    name: 'Custom Photo',
    type: 'photo',
    background: '',
    defaultPadding: 40,
    defaultTextColor: '#ffffff',
  }
];
